name = "event-planner-api"
main = "src/index.ts"
compatibility_date = "2024-08-01"

# Set the following secrets before deploying:
#   wrangler secret put DATABASE_URL
#   wrangler secret put ACCESS_TOKEN_SECRET
#   wrangler secret put REFRESH_TOKEN_SECRET
